QuickSort

In [1]:
quicksort(xs) = quicksort!(copy(xs))
quicksort!(xs) = quicksort!(xs, 1, length(xs))

function quicksort!(xs, lo, hi)
    if lo < hi
        p = partition(xs, lo, hi)
        quicksort!(xs, lo, p - 1)
        quicksort!(xs, p + 1, hi)
    end
    return xs
end

function partition(xs, lo, hi)
    pivot = div(lo + hi, 2)
    pvalue = xs[pivot]
    xs[pivot], xs[hi] = xs[hi], xs[pivot]
    j = lo
    @inbounds for i in lo:hi-1
        if xs[i] <= pvalue
            xs[i], xs[j] = xs[j], xs[i]
            j += 1
        end
    end
    xs[j], xs[hi] = xs[hi], xs[j]
    return j
end

partition (generic function with 1 method)

In [2]:
quicksort([3, 6, 3, 4, 5, 1])

6-element Array{Int64,1}:
 1
 3
 3
 4
 5
 6

In [4]:
using Random: seed!
seed!(0xdeadbeef)
xs = randn(10_000_000)
@time quicksort(xs)

  0.964285 seconds (20.62 k allocations: 77.315 MiB, 4.61% gc time)


10000000-element Array{Float64,1}:
 -5.201821821719352
 -5.050624909871284
 -4.983261442674312
 -4.974985552832985
 -4.893857076120602
 -4.864517550048943
 -4.85004091215009 
 -4.811551905035468
 -4.785936931795382
 -4.758123564483724
 -4.751953182949212
 -4.751136270866197
 -4.700641597803617
  ⋮                
  4.643556492102544
  4.664239936011457
  4.682333119886756
  4.685774543279274
  4.695170058903736
  4.710676182931005
  4.824126039132785
  4.889103328580121
  4.920689915842902
  4.976832282177101
  5.16998796753511 
  5.293639671892019

In [6]:
quicksort(["Bob", "Alick", "Dave", "Eve", "Charlie"])

5-element Array{String,1}:
 "Alick"  
 "Bob"    
 "Charlie"
 "Dave"   
 "Eve"    

In [7]:
x = 100

100

In [8]:
η = 0.1

0.1

In [9]:
漢字変数 = η

0.1

In [10]:
for i in 1:10
    xx = i
end
xx

UndefVarError: UndefVarError: xx not defined

In [11]:
if true
    yy = 10
end
yy

10

In [12]:
Int64

Int64

In [13]:
Float64

Float64

In [14]:
Complex{Float64}

Complex{Float64}

In [15]:
π

π = 3.1415926535897...

In [16]:
isa(π, Irrational)

true

In [17]:
typeof(24)

Int64

In [18]:
typeof(3//1)

Rational{Int64}

In [19]:
typeof(nothing)

Nothing

In [20]:
1 isa Int

true

In [21]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [22]:
xs = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [23]:
xs[1]

1

In [24]:
xs[2] = 200

200

In [25]:
xs[end]

5

In [26]:
xs[end] == xs[5]

true

In [27]:
isa([1, 2, 3], Vector)

true

In [28]:
[1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [29]:
x = [1 2 3;
     4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [30]:
1:10

1:10

In [31]:
typeof(1:10)

UnitRange{Int64}

In [32]:
'a':'z'

'a':1:'z'

In [33]:
for i in 0:10:90
    println(i)
end

0
10
20
30
40
50
60
70
80
90


In [34]:
for i in 5:-1:1
    println(i)
end

5
4
3
2
1


In [36]:
x = Dict("foo" => 1, "bar" => 2)

Dict{String,Int64} with 2 entries:
  "bar" => 2
  "foo" => 1

In [37]:
x["foo"]

1

In [39]:
isconcretetype(Int64)

true

In [40]:
Int32 <: Integer

true

In [41]:
isconcretetype(Integer)

false

In [42]:
isabstracttype(Integer)

true

In [43]:
supertype(Bool)

Integer

In [45]:
subtypes(Integer)

3-element Array{Any,1}:
 Bool    
 Signed  
 Unsigned

In [46]:
subtypes(Signed)

6-element Array{Any,1}:
 BigInt
 Int128
 Int16 
 Int32 
 Int64 
 Int8  

In [48]:
function tracetype(t)
    print(t)
    while t!= supertype(t)
        print(" <: ")
        t = supertype(t)
        print(t)
    end
    println()
end

tracetype (generic function with 1 method)

In [49]:
tracetype(Int64)

Int64 <: Signed <: Integer <: Real <: Number <: Any


In [50]:
tracetype(BigInt)

BigInt <: Signed <: Integer <: Real <: Number <: Any


In [51]:
typeof([1.0, 2.0, 3.0])

Array{Float64,1}

In [60]:
mutable struct Person
    name::String
    age::Int
end

struct Location
    x::Float64
    y::Float64
end

In [61]:
person = Person("Yamada Tanaka", 34)

Person("Yamada Tanaka", 34)

In [62]:
person.age,  person.name

(34, "Yamada Tanaka")

In [63]:
person.age += 1

35

In [64]:
person

Person("Yamada Tanaka", 35)

In [65]:
loc = Location(1.0, 2.0)

Location(1.0, 2.0)

In [66]:
loc.x += 2

ErrorException: setfield! immutable struct of type Location cannot be changed

In [67]:
function dist(p, q)
    dx = p[1] - q[1]
    dy = p[2] - q[2]
    sqrt((dx)^2 + (dy)^2)
end

dist (generic function with 1 method)

In [68]:
dist((0, 0), (3, 4))

5.0

In [69]:
dist(p, q) = sqrt((p[1] - q[1])^2 + (p[2] - q[2])^2)

dist (generic function with 1 method)

In [70]:
dist((0, 0), (3, 4))

5.0

In [71]:
ktop(xs, k=3) = sort(xs)[1:k]

ktop (generic function with 2 methods)

In [73]:
ktop([1, 5, 3, 2, 6])

3-element Array{Int64,1}:
 1
 2
 3

In [74]:
function pathlength(p, q, rs...)
    len = dist(p, q)
    for r in rs
        len += dist(q,r)
        q = r
    end
    return len
end


pathlength (generic function with 1 method)

In [75]:
pathlength((0, 0), (1, 1))

1.4142135623730951

In [76]:
pathlength((0, 0), (1, 1), (1, 2), (0, 0))

4.650281539872885

In [77]:
function add(x::Int, y::Int)
    return x + y
end

add (generic function with 1 method)

In [78]:
add(1, 2)

3

In [79]:
add(1.0, 2.0)

MethodError: MethodError: no method matching add(::Float64, ::Float64)

In [80]:
function add(x::Float64, y::Float64)
    return x + y
end

add (generic function with 2 methods)

In [81]:
add(1.0, 2.0)

3.0

In [82]:
add(1, 2)

3

In [83]:
function add(x::Number, y::Number)
    return x + y
end

add (generic function with 3 methods)

In [84]:
add(BigInt(1), BigFloat(1))

2.0

In [85]:
struct RGB
    r::UInt8
    g::UInt8
    b::UInt8
    
    function RGB(r, g, b)
        @assert 0 <= r <= 255
        @assert 0 <= g <= 255
        @assert 0 <= b <= 255
        return new(r, g, b)
    end 
end

In [87]:
RGB(1, 2, 3)

RGB(0x01, 0x02, 0x03)

In [88]:
RGB(2, 300, 2)

AssertionError: AssertionError: 0 <= g <= 255

In [89]:
RGB(x) = RGB(x, x, x)

RGB

In [90]:
RGB() = RGB(0)

RGB

In [91]:
RGB(), RGB(10), RGB(10, 20, 30)

(RGB(0x00, 0x00, 0x00), RGB(0x0a, 0x0a, 0x0a), RGB(0x0a, 0x14, 0x1e))

In [92]:
x = 2.1

2.1

In [93]:
2x

4.2

In [94]:
4x^2 + 3x - 2

21.94

In [95]:
x = range(0, stop=1, length=50);

In [96]:
4sin.(2x) - 3cos.(4x)

50-element Array{Float64,1}:
 -3.0                
 -2.8267897373141215 
 -2.6339373233305805 
 -2.4219133558638326 
 -2.1913188324640127 
 -1.9428824987789626 
 -1.677457339318942  
 -1.3960162317568687 
 -1.0996467914829426 
 -0.7895454385442837 
 -0.4670107243016668 
 -0.13343596009188374
  0.20969880513734385
  ⋮                  
  6.996871635711436  
  6.996458834488029  
  6.969421660503003  
  6.9159064004967    
  6.836202476105568  
  6.730740627863947  
  6.60009021313547   
  6.444955635692603  
  6.266171930354854  
  6.064699531632904  
  5.841618260670547  
  5.598120569893563  

In [97]:
[x for x in 1:4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [98]:
[x*y for x in 1:4, y in 1:5]

4×5 Array{Int64,2}:
 1  2   3   4   5
 2  4   6   8  10
 3  6   9  12  15
 4  8  12  16  20

In [99]:
[x for x in 1:10 if isodd(x)]

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [100]:
Dict(c => i for (i, c) in enumerate('a': 'z'))

Dict{Char,Int64} with 26 entries:
  'n' => 14
  'f' => 6
  'w' => 23
  'd' => 4
  'e' => 5
  'o' => 15
  'h' => 8
  'j' => 10
  'i' => 9
  'k' => 11
  'r' => 18
  's' => 19
  't' => 20
  'q' => 17
  'y' => 25
  'a' => 1
  'c' => 3
  'p' => 16
  'm' => 13
  'z' => 26
  'g' => 7
  'v' => 22
  'l' => 12
  'u' => 21
  'x' => 24
  'b' => 2

In [101]:
x = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [102]:
x'

3×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [103]:
transpose(x)

3×2 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [104]:
x -> 2x

#11 (generic function with 1 method)

In [105]:
map(x -> 2x, [1, 2, 3])

3-element Array{Int64,1}:
 2
 4
 6

In [106]:
map([1, 2, 3]) do x
    2x
end

3-element Array{Int64,1}:
 2
 4
 6

In [123]:
open("sample.txt") do io
    for (n, line) in enumerate(eachline(io))
        println("$n:$line")
    end
end

In [111]:
r"\w-\d\w+"

r"\w-\d\w+"

In [114]:
match(r"\w-\d\w+", "B-2 Spirit")

In [115]:
v"1.2.3"

v"1.2.3"

In [117]:
`ls -la`

`ls -la`

In [118]:
run(`ls -la`)

total 80
drwxr-xr-x  4 tanimu  staff    128 May 29 14:33 .
drwxr-xr-x  7 tanimu  staff    224 May 29 13:27 ..
drwxr-xr-x  3 tanimu  staff     96 May 29 13:28 .ipynb_checkpoints
-rw-r--r--  1 tanimu  staff  37161 May 29 14:33 Untitled.ipynb


Process(`ls -la`, ProcessExited(0))

In [119]:
run(`touch sample.txt`)

Process(`touch sample.txt`, ProcessExited(0))

In [124]:
run(`cat -n sample.txt`)

Process(`cat -n sample.txt`, ProcessExited(0))

In [125]:
x = 3.14

3.14

In [126]:
@show x

x = 3.14


3.14

In [129]:
insertionsort(xs) = insertionsort!(copy(xs))
function insertionsort!(xs)
    @show xs
    for i in 2:length(xs)
        j = i
        while j > i && xs[j-1] > xs[j]
            xs[j-1], xs[j] = xs[j], xs[j-1]
            j -= 1
        end
        @show xs
    end
    xs
end

insertionsort! (generic function with 1 method)

In [130]:
insertionsort([6, 5, 4, 3, 56, 7, 4, 34])

xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]
xs = [6, 5, 4, 3, 56, 7, 4, 34]


8-element Array{Int64,1}:
  6
  5
  4
  3
 56
  7
  4
 34

In [131]:
@assert x == 1

AssertionError: AssertionError: x == 1

In [133]:
insertionsort(xs) = insertionsort!(copy(xs))

function insertionsort!(xs)
    #@show xs
    @inbounds for i in 2:length(xs)
        j = i
        while j > 1 && xs[j-1] > xs[j]
            xs[j-1], xs[j] = xs[j], xs[j-1]
            j -= 1
        end
    end
    xs
end

insertionsort([1.0, 0.0])

2-element Array{Float64,1}:
 0.0
 1.0

In [134]:
x = zeros(Float64, 4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [135]:
x = zeros(Float64, (3, 4))

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [136]:
x = zeros(Float64, (4, 3, 2))

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [137]:
ones(Float64, 4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [138]:
using LinearAlgebra

In [142]:
zeros(3, 3) + 4I

3×3 Array{Float64,2}:
 4.0  0.0  0.0
 0.0  4.0  0.0
 0.0  0.0  4.0

In [143]:
[Float64(i > j) for i in 1:4 , j in 1:3]

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 1.0  0.0  0.0
 1.0  1.0  0.0
 1.0  1.0  1.0

In [144]:
x = [1.0, 2.0, 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [145]:
x .+ 1.0

3-element Array{Float64,1}:
 2.0
 3.0
 4.0

In [147]:
x + 4x

3-element Array{Float64,1}:
  5.0
 10.0
 15.0

In [148]:
x

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [149]:
2x ./ x

3-element Array{Float64,1}:
 2.0
 2.0
 2.0

In [150]:
dot(x, x)

14.0

In [152]:
A = [Float64(i + j) for i in 1:2, j in 1:3]

2×3 Array{Float64,2}:
 2.0  3.0  4.0
 3.0  4.0  5.0

In [153]:
A * x

2-element Array{Float64,1}:
 20.0
 26.0

In [154]:
A' * A

3×3 Array{Float64,2}:
 13.0  18.0  23.0
 18.0  25.0  32.0
 23.0  32.0  41.0

In [155]:
x' * x

14.0

In [156]:
A'A

3×3 Array{Float64,2}:
 13.0  18.0  23.0
 18.0  25.0  32.0
 23.0  32.0  41.0

In [1]:
module ModFoo

struct Foo
    x
end

function show(x)
    print("!!" * string(x) * "!!")
end

end

Main.ModFoo

In [2]:
f = ModFoo.Foo("something")

Main.ModFoo.Foo("something")

In [3]:
ModFoo.show(f)

!!Main.ModFoo.Foo("something")!!

In [4]:
show(f)

Main.ModFoo.Foo("something")

In [5]:
Main

Main

In [7]:
Main.quicksort([3, 1, 2])

UndefVarError: UndefVarError: quicksort not defined

In [8]:
Main.f

Main.ModFoo.Foo("something")

In [9]:
Main.ModFoo

Main.ModFoo

In [1]:
module Geo

export Point, distance, iswithin, move

struct Point
    x::Float64
    y::Float64
    z::Float64
end

distance(a::Point, b::Point) = sqrt(sqdist(a, b))
iswithin(p::Point, c::Point, r::Real) = sqdist(p, c) <= r^2

function move(p::Point, dx, dy, dz)
    return Point(p.x + dx, p.y + dy, p.z + dz)
end

sqdist(a::Point, b::Point) = (a.x - b.x)^2 + (a.y - b.y) ^2 + (a.z - b.z)^2

end

Main.Geo

In [2]:
using .Geo

In [3]:
p0 = Point(0, 0, 0)
p1 = Point(1, 1, 1)

Point(1.0, 1.0, 1.0)

In [4]:
distance(p0, p1)

1.7320508075688772

In [5]:
iswithin(p1, p0, 1.7)

false

In [6]:
move(p1, -1, 0, 0)

Point(0.0, 1.0, 1.0)

In [7]:
iswithin(p1, p0, 1.7)

false

In [8]:
sqdist(p0, p1)

UndefVarError: UndefVarError: sqdist not defined

In [9]:
Geo.sqdist(p0, p1)

3.0

In [10]:
# 最初に実行するときだけ，下のコメントを消して実行する
using Pkg
Pkg.update()
Pkg.add("Optim")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.1/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.1/Manifest.toml`
 [no changes]
 Resolving package versions...
 Installed Calculus ─────────────── v0.4.1
 Installed Missings ─────────────── v0.4.1
 Installed NLSolversBase ────────── v7.3.1
 Installed CommonSubexpressions ─── v0.2.0
 Installed OrderedCollections ───── v1.1.0
 Installed BinDeps ──────────────── v0.8.10
 Installed StaticArrays ─────────── v0.10.3
 Installed Optim ────────────────── v0.18.1
 Installed PositiveFactorizations ─ v0.2.2
 Installed DiffEqDiffTools ──────── v0.10.1
 Installed ForwardDiff ──────────── v0.10.3
 Installed DiffResults ──────────── v0.0.4
 Installed LineSearches ─────────── v7.0.1
 Installed DataStructures ───────── v0.15.0
 Installed StatsBase ────────────── v0.30.0
 Installed SpecialFunctions ─

In [11]:
using Optim # It takes a bit long time to load the pkg just after installing it.

┌ Info: Precompiling Optim [429524aa-4258-5aef-a3af-852621145aeb]
└ @ Base loading.jl:1186


In [12]:
func(x, a=1, b=100) = (a - x[1])^2 + b * (x[2] - x[1]^2)^2

func (generic function with 3 methods)

In [13]:
optimize(func, [10.0, 10.0])

Results of Optimization Algorithm
 * Algorithm: Nelder-Mead
 * Starting Point: [10.0,10.0]
 * Minimizer: [1.0000076575345525,1.0000090769441363]
 * Minimum: 3.950131e-09
 * Iterations: 103
 * Convergence: true
   *  √(Σ(yᵢ-ȳ)²)/n < 1.0e-08: true
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 199

In [14]:
versioninfo()

Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
